backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site"
    label: "Site Settings"
    files:
      - label: "General"
        name: "general"
        file: "content/site.md"
        fields:
          - { label: "Logo", name: "logo", widget: "image" }
  - name: "navbar"
    label: "Navbar"
    folder: "content/navbar"
    create: true
    slug: "{{fields.label}}"
    fields:
      - { label: "Label", name: "label", widget: "string" }
      - { label: "Link", name: "link", widget: "string", required: false }
      - label: "Dropdown Items"
        name: "dropdown"
        widget: "list"
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "Link", name: "link", widget: "string" }

  - name: "hero"
    label: "Hero Section"
    files:
      - label: "Hero"
        name: "hero"
        file: "content/hero.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "CTA Text", name: "cta_text", widget: "string" }
          - { label: "CTA Link", name: "cta_link", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }

  - name: "statistics"
    label: "Data Statistics"
    files:
      - label: "Statistics"
        name: "statistics"
        file: "content/statistics.md"
        fields:
          - label: "Section Title"
            name: "section_title"
            widget: "string"
            default: "Our Achievements"
          - label: "Section Description"
            name: "section_description"
            widget: "string"
            default: "Some of our key numbers."
          - label: "Stats"
            name: "stats"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Value", name: "value", widget: "string" }

  - name: "products"
    label: "Products/Services"
    folder: "content/products"
    create: true
    slug: "{{fields.name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "products_section"
    label: "Products Section Settings"
    files:
      - label: "Products Section"
        name: "products_section"
        file: "content/products_section.md"
        fields:
          - { label: "Section Title", name: "section_title", widget: "string", default: "Our Products & Services" }
          - { label: "Section Description", name: "section_description", widget: "string", default: "Discover our innovative solutions designed to help your business grow and succeed in today's competitive market." }

  - name: "partners"
    label: "Partners"
    folder: "content/partners"
    create: true
    slug: "{{fields.name}}"
    fields:
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Website", name: "website", widget: "string", required: false }

  - name: "partners_section"
    label: "Partners Section Settings"
    files:
      - label: "Partners Section"
        name: "partners_section"
        file: "content/partners_section.md"
        fields:
          - { label: "Section Title", name: "section_title", widget: "string", default: "Trusted by Industry Leaders" }
          - { label: "Section Description", name: "section_description", widget: "string", default: "We're proud to work with some of the most innovative companies in the industry." }

  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    slug: "{{fields.name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Quote", name: "quote", widget: "text" }
      - { label: "Photo", name: "photo", widget: "image", required: false }

  - name: "testimonials_section"
    label: "Testimonials Section Settings"
    files:
      - label: "Testimonials Section"
        name: "testimonials_section"
        file: "content/testimonials_section.md"
        fields:
          - { label: "Section Title", name: "section_title", widget: "string", default: "What Our Clients Say" }
          - { label: "Section Description", name: "section_description", widget: "string", default: "Hear from the people who trust us to deliver exceptional results for their businesses." }

  - name: "contact"
    label: "Contact"
    files:
      - label: "Contact Info"
        name: "contact"
        file: "content/contact.md"
        fields:
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Map Embed", name: "map_embed", widget: "text", required: false }

  - name: "contact_section"
    label: "Contact Section Settings"
    files:
      - label: "Contact Section"
        name: "contact_section"
        file: "content/contact_section.md"
        fields:
          - { label: "Section Title", name: "section_title", widget: "string", default: "Get in Touch" }
          - { label: "Section Description", name: "section_description", widget: "string", default: "Ready to start your next project? Let's discuss how we can help you achieve your goals." } 